version: "2"
plugins: 
  eslint:
    enabled: true
  csslint:
    enabled: false
  git-legal:
    enabled: true
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
#    exclude_patterns:
#      - config/engines.yml
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true

exclude_patterns:
- "config/"
- "**/node_modules/"
- "**/models/"
- "**/test/"
- ".github/"
- "migrations/**"
- "public/css/**"
