version: "2"
plugins: 
  eslint:
    enabled: true
  git-legal:
    enabled: true
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: false
exclude_patterns:
- "config/"
- "**/node_modules/"
- "**/models/"
- "**/test/"
- ".github/"
- "migrations/**"
- "public/css/**"
