image: node:latest

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: family-graph
  MYSQL_ROOT_PASSWORD: mysql_strong_password
  CODECOV_TOKEN: cc074b5e-0c59-4e4e-822e-0b2464274e70
  sqlhost: mysql
  sqluser: root
  sqlpass: mysql_strong_password
  sqlbase: family-graph

cache:
  paths:
  - node_modules/

stages:
  - init
  - test
  - extra

mysql_connect:
  stage: init
  image: mysql
  script:
    - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql $MYSQL_DATABASE
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql mysql -e "SET PASSWORD FOR 'root'@'%' = OLD_PASSWORD('$MYSQL_ROOT_PASSWORD');"
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql mysql -e "FLUSH PRIVILEGES;"
    - mysql -B --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql $MYSQL_DATABASE < ./struct.sql

test:codecov:
  stage: test
  script:
    - npm install -g codecov
    - npm install
    - npm run coveralls

test:coveralls:
  stage: test
  script:
    - npm install -g coveralls
    - npm install
    - npm test && codecov

lint:
  stage: extra
  script:
    - npm install
    - npm run lint

vulnerabilities:
  stage: extra
  script:
    - npm install
    - npm run nsp