image: node:latest

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: family-graph
  MYSQL_ROOT_PASSWORD: mysql_strong_password
  CODECOV_TOKEN: cc074b5e-0c59-4e4e-822e-0b2464274e70
  sqlhost: mysql
  sqluser: root

cache:
  paths:
  - node_modules/

stages:
  - init
  - test
  - extra

mysql_connect:
  stage: extra
  image: mysql
  before_script:
    - mysql -B --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql $MYSQL_DATABASE < ./struct.sql
  script:
    - mysql -B --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql $MYSQL_DATABASE -e "SHOW TABLES;"

test:codecov:
  stage: test
  before_script:
    - npm install -g codecov sequelize
    - npm run migrations
  script:
    - npm install
    - npm run coveralls

test:coveralls:
  stage: test
  before_script:
    - npm install -g coveralls sequelize
    - npm run migrations
  script:
    - npm install
    - npm test && codecov

lint:
  stage: extra
  script:
    - npm install
    - npm run lint

vulnerabilities:
  stage: extra
  script:
    - npm install
    - npm run nsp