image: node:latest

services:
  - mysql:5.7

variables:
  NODE_ENV: "testing"
  MYSQL_DATABASE: family-graph
  MYSQL_ROOT_PASSWORD: mysql_strong_password
  CODECOV_TOKEN: cc074b5e-0c59-4e4e-822e-0b2464274e70
  sqlhost: mysql
  sqluser: root

cache:
  paths:
  - node_modules/

stages:
  - init
  - test
  - extra

mysql_connect:
  stage: init
  image: mysql
  before_script:
    - mysql -B --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql $MYSQL_DATABASE < ./struct.sql
  script:
    - mysql -B --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql $MYSQL_DATABASE -e "SHOW TABLES;"

migrations:
  stage: init
  before_script:
    - npm install
  script:
    - npm run migrations


codecov:
  stage: test
  before_script:
    - npm install
    - npm run migrations
    - npm install -g codecov
  script:
    - npm run coveralls

coveralls:
  stage: test
  before_script:
    - npm install
    - npm run migrations
    - npm install -g coveralls
  script:
    - npm test && codecov

lint:
  stage: extra
  before_script:
    - npm install
  script:
    - npm run lint

vulnerabilities:
  stage: extra
  before_script:
    - npm install
  script:
    - npm run nsp