image: node:latest

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: family-graph
  MYSQL_ROOT_PASSWORD: mysql_strong_password
  CODECOV_TOKEN: cc074b5e-0c59-4e4e-822e-0b2464274e70

cache:
  paths:
  - node_modules/

test:mysql_connect:
  image: mysql
  script:
    - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE" $MYSQL_DATABASE < ./test/struct.sql

test:lint:
  script:
    - npm install
    - npm run lint

test:vulnerabilities:
  script:
    - npm install
    - npm run nsp

test:node:
  script:
    - npm install -g codecov
    - npm install
    - npm test && codecov