image: node:latest

services:
  - mysql:5.7

variables:
  NODE_ENV: "testing"
  MYSQL_DATABASE: family-graph
  MYSQL_ROOT_PASSWORD: mysql_strong_password
  CODECOV_TOKEN: cc074b5e-0c59-4e4e-822e-0b2464274e70
  sqlhost: mysql
  sqluser: root

cache:
  paths:
  - node_modules/

stages:
  - test

migrations:
  stage: test
  before_script:
    - npm install
  script:
    - npm run migrations

codecov:
  stage: test
  before_script:
    - npm install
    - npm run migrations
    - npm install -g codecov
  script:
    - npm run coverage
    - codecov

lint:
  stage: test
  services: []
  before_script:
    - npm install
  script:
    - npm run lint

vulnerabilities:
  stage: test
  services: []
  before_script:
    - npm install
  script:
    - npm run nsp