language: node_js # Sets which engine use to build the project
node_js: "node" # Specifies node version to use "node"="latest"
env:
  NODE_ENV: "testing"
  MYSQL_DATABASE: testbase
  MYSQL_ROOT_PASSWORD: 
  NODE_API_DB_PORT: 3306
  sqlhost: localhost
  sqluser: travis
service:
  - mysql
cache:
  directories:
    - "node_modules"
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS testbase;"
install:
  - npm ci
cache:
  directories:
  - "$HOME/.npm"
before_script:
  - cp ./migrations/config.js.travis ./migrations/config.js
#  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#  - chmod +x ./cc-test-reporter
#  - ./cc-test-reporter before-build
script:
  - npm i -g codecov
  - npm run migrations
  - npm run coverage
#after_script:
#  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT