language: node_js # Sets which engine use to build the project
node_js: "node" # Specifies node version to use "node"="latest"
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
service: mysql
cache:
  directories:
    - "node_modules"
  yarn: true
script:
  - npm i -g codecov
  - npm run migrations
  - npm run coverage
  - codecov